//common
export const APP_LOAD = 'APP_LOAD';
export const REDIRECT = 'REDIRECT';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const REGISTER = 'REGISTER';
export const LOGIN_PAGE_UNLOADED = 'LOGIN_PAGE_UNLOADED';
export const REGISTER_PAGE_UNLOADED = 'REGISTER_PAGE_UNLOADED';
export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';


//agendaList
export const GET_LIST_AGENDA = 'GET_LIST_AGENDA';
export const GET_LIST_TEMPLATE = 'GET_LIST_TEMPLATE';
export const GET_LIST_TRASH = 'GET_LIST_TRASH';

//agenda
export const AGENDA_UPDATE_FIELD = 'AGENDA_UPDATE_FIELD';
export const AGENDA_CREATE = 'AGENDA_CREATE';
export const AGENDA_UPDATE = 'AGENDA_UPDATE';
export const AGENDA_SAVE = 'AGENDA_SAVE';
export const AGENDA_CLOSE_DIALOG = 'AGENDA_CLOSE_DIALOG';
export const AGENDA_MENU_ITEM_TAP = 'AGENDA_MENU_ITEM_TAP';
export const AGENDA_GET_DETAIL = 'AGENDA_GET_DETAIL';


//auth
export const AUTH_UPDATE_FIELD = 'AUTH_UPDATE_FIELD';
export const AUTH_CHANGE_INDEX = 'AUTH_CHANGE_INDEX';

//agendaItem
export const AI_ACTION_MOUSE_OVER = 'AI_ACTION_MOUSE_OVER';
export const AI_ACTION_MOUSE_OUT = 'AI_ACTION_MOUSE_OUT';
export const AI_ACTION_NAV_DETAIL = 'AI_ACTION_NAV_DETAIL';
export const AI_ACTION_LOGIC_DEL = 'AI_ACTION_LOGIC_DEL';
export const AI_ACTION_LOGIC_DEL_UNDO = 'AI_ACTION_LOGIC_DEL_UNDO';
export const AI_ACTION_DEL = 'AI_ACTION_DEL';

//agendaPlay
export const AP_ACTION_GET_DETAIL = 'AP_ACTION_GET_DETAIL';
export const AP_ACTION_UPDATE_TIMER = 'AP_ACTION_UPDATE_TIMER';

//header
export const H_ACTION_TOGGLE = 'H_ACTION_TOGGLE';
export const H_ACTION_MOUSEOVER = 'H_ACTION_MOUSEOVER';
export const H_ACTION_MOUSEOUT = 'H_ACTION_MOUSEOUT';


